/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Add_PostCourse extends javax.swing.JFrame {
    DB_Post dbops=new DB_Post();
    //PostGraduate_CourseDetail pgc = new PostGraduate_CourseDetail();
    /**
     * Creates new form Add_PostCourse
     */
    public Add_PostCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ddFaculty = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddCourseId = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ddMainSubject1 = new javax.swing.JComboBox();
        ddMainSubject2 = new javax.swing.JComboBox();
        ddSubject1 = new javax.swing.JComboBox();
        ddSubject2 = new javax.swing.JComboBox();
        ddSubject3 = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ddNumOfYears = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 133, 227));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Details"));

        jLabel1.setText("Faculty");

        ddFaculty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ddFaculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "School of Business", "School of Computing", "School of Engineering" }));
        ddFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddFacultyItemStateChanged(evt);
            }
        });

        jLabel2.setText("Reg Id");

        jLabel3.setText("Course Id");

        ddCourseId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ddCourseId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddCourseIdItemStateChanged(evt);
            }
        });

        jLabel4.setText("Main Subject 1");

        jLabel5.setText("Main Subject 2");

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Credit 2 Subjects");

        jLabel6.setText("Subject 1");

        jLabel7.setText("Subject 2");

        jLabel8.setText("Subject 3");

        btnBack.setBackground(new java.awt.Color(106, 14, 209));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setText("Number Of Years");

        ddNumOfYears.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddNumOfYears.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "02" }));

        btnSubmit.setBackground(new java.awt.Color(106, 14, 209));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel3))
                                    .addGap(1, 1, 1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addComponent(ddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddMainSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddNumOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ddNumOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddMainSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSubmit)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddFacultyItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddFaculty.getSelectedIndex()>=0){
                this.ddCourseId.setModel(new DefaultComboBoxModel(this.getcourseid(this.ddFaculty.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddFacultyItemStateChanged

    private void ddCourseIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddCourseIdItemStateChanged

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject1.setModel(new DefaultComboBoxModel(this.getmainsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject2.setModel(new DefaultComboBoxModel(this.getmainsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject1.setModel(new DefaultComboBoxModel(this.getsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject2.setModel(new DefaultComboBoxModel(this.getsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject3.setModel(new DefaultComboBoxModel(this.getsubject3(this.ddCourseId.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddCourseIdItemStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        PostGraduate_CourseDetail pgc=new PostGraduate_CourseDetail();

        int x=dbops.checkStudentId4(txtRegId.getText(),ddCourseId.getSelectedItem().toString());
        if(x==1){
            pgc.setFaculty(ddFaculty.getSelectedItem().toString());
            pgc.setRegId(Integer.parseInt(txtRegId.getText()));
            pgc.setCourseId((String) (ddCourseId.getSelectedItem()));
            pgc.setNumOfYears(Integer.parseInt(ddNumOfYears.getSelectedItem().toString()));
            pgc.setMainSubject1(ddMainSubject1.getSelectedItem().toString());
            pgc.setMainSubject2(ddMainSubject2.getSelectedItem().toString());
            pgc.setSubject1(ddSubject1.getSelectedItem().toString());
            pgc.setSubject2(ddSubject2.getSelectedItem().toString());
            pgc.setSubject3(ddSubject3.getSelectedItem().toString());

            dbops.PostGraduateCourse(pgc);
            JOptionPane.showMessageDialog(this, "Successfully Inserted");
            txtRegId.setText("");

    }//GEN-LAST:event_btnSubmitActionPerformed
     else if(x==0){
            JOptionPane.showMessageDialog(this, "Reg id and Course id already exist");
            txtRegId.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "error occured");
        }
    }
     public String[] getcourseid(String pais){
       String[] courseid=new String[5];
       if(pais.equalsIgnoreCase("School of Computing")){
       courseid[0]="Select";
       courseid[1]="cs 1.1";
       courseid[2]="cs 1.2";
       courseid[3]="cs 2.1";
       courseid[4]="cs 2.2";
       
       
       }
       
        if(pais.equalsIgnoreCase("School of Business")){
       courseid[0]="Select";
       courseid[1]="bus 1.1";
       courseid[2]="bus 1.2";
       courseid[3]="bus 2.1";
       courseid[4]="bus 2.2";
       
       
       }
       
       if(pais.equalsIgnoreCase("School of Engineering")){
       courseid[0]="Select";
       courseid[1]="eng 1.1";
       courseid[2]="eng 1.2";
       courseid[3]="eng 2.1";
       courseid[4]="eng 2.2";
       }
       
       return courseid; 
   
   } 
    
    
    public String[] getmainsubject1(String pais){
        String[] mainsubject1=new String[2];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Calculus";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Management Theory and Practice";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Environment and Energy Studies";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
          
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Research Methods";
           
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            
            mainsubject1[0]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Management of Change";
        }   
         
          
          return mainsubject1;
              
    }
    
    public String[] getmainsubject2(String pais){
        String[] mainsubject1=new String[1];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="ICT Tools";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Heat and Mass Transfer";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Human Resource Management";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Ethics & Values";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
             
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Data Structure and Algorithms";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
           
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Marketing Management";
        }   
         
          
          return mainsubject1;
              
    }
    
    public String[] getsubject1(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="Data Structure and Algorithms";
            mainsubject1[1]="ICT Tools";
            mainsubject1[2]="Database Systems";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Physics";
            mainsubject1[1]="Kinematics";
            mainsubject1[2]="Mechanics of Solids";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
           mainsubject1[0]="Taxation 1";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="IT Risk Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Law for Engineers";
            mainsubject1[1]="Capston Course (Mechanical Engineering)";
            mainsubject1[2]="Yog and Meditation";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
         
          
          return mainsubject1;
              
    }
    
     public String[] getsubject2(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
           mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
              mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
             mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }   
         
          
          
          
          return mainsubject1;
              
    }
    
    public String[] getsubject3(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
     
           
          return mainsubject1;
              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_PostCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_PostCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_PostCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_PostCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_PostCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox ddCourseId;
    private javax.swing.JComboBox ddFaculty;
    private javax.swing.JComboBox ddMainSubject1;
    private javax.swing.JComboBox ddMainSubject2;
    private javax.swing.JComboBox ddNumOfYears;
    private javax.swing.JComboBox ddSubject1;
    private javax.swing.JComboBox ddSubject2;
    private javax.swing.JComboBox ddSubject3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtRegId;
    // End of variables declaration//GEN-END:variables
}
